sonar.organization=cruz-blanca-tech
sonar.projectKey=Cruz-Blanca-Tech_cruz-blanca-app
sonar.projectName=Cruz Blanca - Frontend App

# Directorio fuente
sonar.sources=src

# Codificación
sonar.sourceEncoding=UTF-8

# Exclusiones
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/*.config.js,**/*.config.mjs,**/*.config.ts
sonar.coverage.exclusions=**/*
